# Generated by Django 4.1.1 on 2022-11-07 19:58

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='images/user/default.png', help_text='Upload a user image', upload_to=account.models.directory_path, verbose_name='image'),
        ),
    ]
