# Generated by Django 4.1.1 on 2022-10-24 00:14

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='images/default.png', help_text='Upload a product image', upload_to=store.models.product_directory_path, verbose_name='image'),
        ),
    ]
