# Generated by Django 4.1.1 on 2022-10-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_brand_product_rating_product_rating_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, error_messages={'name': {'max_length': 'The rating must be between 0 and 5.'}}, help_text='Maximum 5', max_digits=2, verbose_name='rating'),
        ),
    ]
